### Question 1
Random Forest Classifier : Perform Classification on IRIS DATASET and MNIST DATASET using Random Forest Classifier.

In [98]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report
import numpy as np

df_iris = pd.read_csv('iris.data')

print("Shape of the dataset:",df_iris.shape,"\n")
print("Dataset:\n",df_iris.head())

X = df_iris.iloc[:,:-1].values
y = df_iris.iloc[:,-1].values

y = LabelEncoder().fit_transform(y)

#splitting the dataset for training  and validation
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state = 100)

clf = RandomForestClassifier(random_state = 100)

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Test dataset:",X_test)
print("Predicted classes:",y_pred)

print("Accuracy:",metrics.accuracy_score(y_test,y_pred)*100)

print("Confusion matrix:\n",confusion_matrix(y_test, y_pred))

print("Classification report:\n",classification_report(y_test,y_pred))


Shape of the dataset: (149, 5) 

Dataset:
    5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
Test dataset: [[7.2 3.  5.8 1.6]
 [4.8 3.  1.4 0.1]
 [6.  2.2 5.  1.5]
 [5.4 3.9 1.3 0.4]
 [6.7 3.3 5.7 2.1]
 [7.7 3.  6.1 2.3]
 [5.5 4.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [5.1 3.8 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [6.5 3.  5.5 1.8]
 [5.2 3.5 1.5 0.2]
 [4.7 3.2 1.6 0.2]
 [6.7 3.  5.2 2.3]
 [5.1 2.5 3.  1.1]
 [6.1 2.9 4.7 1.4]
 [6.  2.9 4.5 1.5]
 [6.3 2.7 4.9 1.8]
 [5.7 2.5 5.  2. ]
 [6.2 2.8 4.8 1.8]
 [5.2 4.1 1.5 0.1]
 [6.3 2.5 5.  1.9]
 [4.8 3.1 1.6 0.2]
 [5.9 3.2 4.8 1.8]
 [5.9 3.  5.1 1.8]
 [6.8 2.8 4.8 1.4]
 [5.1 3.7 1.5 0.4]
 [6.4 2.9 4.3 1.3]
 [5.6 2.8 4.9 2. ]
 [5.8 2.7 3.9 1.2]
 [6.3 3.3 6.  2.5]
 [6.9 3.2 5.7 2.3]
 [4.3 3.  1.1 0.1]
 [5.1 3.5 1.4 0.3]
 [6.9 3.1 4.9 1.5]
 [4.6 3.2 1.4 0.2]
 [5.5 2.6 4.4 1.2]
 [6.3 3.4 5

### LOGISTIC REGRESSION - QUESTION 2
Heart Disease Prediction using Logistic Regression.

In [31]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report
from sklearn import linear_model
import numpy as np
import warnings
warnings.filterwarnings("ignore")



df_framingham = pd.read_csv("framingham.csv")

print("Shape of the dataset:",df_framingham.shape,"\n")

print(df_framingham.isnull().sum())


Shape of the dataset: (4238, 16) 

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64


In [32]:
df_framingham.dropna(inplace = True)
print(df_framingham.isnull().sum())
print(df_framingham.shape)

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64
(3656, 16)


In [33]:
X_dff = df_framingham.iloc[:,:-1].values
y_dff = df_framingham.iloc[:,-1].values

#splitting the dataset for training  and validation
X_dff_train, X_dff_test, y_dff_train, y_dff_test = train_test_split(X_dff,y_dff,test_size = 0.3,random_state = 100)

clf = linear_model.LogisticRegression()

clf.fit(X_dff_train, y_dff_train)
y_dff_pred = clf.predict(X_dff_test)


print("Accuracy:",metrics.accuracy_score(y_dff_test,y_dff_pred)*100)

print("Confusion matrix:\n",confusion_matrix(y_dff_test,y_dff_pred))

print("Classification report:\n",classification_report(y_dff_test,y_dff_pred))


Accuracy: 84.22971741112124
Confusion matrix:
 [[919   3]
 [170   5]]
Classification report:
               precision    recall  f1-score   support

           0       0.84      1.00      0.91       922
           1       0.62      0.03      0.05       175

    accuracy                           0.84      1097
   macro avg       0.73      0.51      0.48      1097
weighted avg       0.81      0.84      0.78      1097



Question 3
### Support Vector Machine (SVM) : Perform iris data classification using SVM .

In [34]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report


In [35]:
#splitting the dataset for training  and validation
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.7,random_state = 100)

svclf = SVC(kernel = 'linear',random_state = 0)

svclf.fit(X_train, y_train)
y_Pred = svclf.predict(X_test)

print("Test dataset:",X_test)
print("Predicted classes:",y_Pred)

print("Accuracy:",metrics.accuracy_score(y_test,y_Pred)*100)

print("Confusion matrix:\n",confusion_matrix(y_test, y_Pred))

print("Classification report:\n",classification_report(y_test,y_Pred))


Test dataset: [[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
Predicted classes: [0 0 1 ... 0 0 0]
Accuracy: 96.77005895924123
Confusion matrix:
 [[3342   31]
 [  95  433]]
Classification report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98      3373
           1       0.93      0.82      0.87       528

    accuracy                           0.97      3901
   macro avg       0.95      0.91      0.93      3901
weighted avg       0.97      0.97      0.97      3901



### Question 4
Naive Bayes : Perform spam email detection using Naive Bayes classifier

In [28]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from collections import Counter
from sklearn.metrics import confusion_matrix,classification_report


In [29]:
label = []
features = [] 
words = []

df_email = pd.read_csv('spam.csv')
print(df_email.shape)
print("First 5 lines of the dataset:\n",df_email.head())

for i in range(df_email.shape[0]):
    blob=str(df_email.iloc[i,1])
    
    words+=blob.split(" ")
    
for i in range(len(words)):
    if not words[i].isalpha():
        words[i]=""


word_dict = Counter(words)
del word_dict[""]
word_dict = word_dict.most_common(3000)

for i in range(df_email.shape[0]):
    blob=df_email.iloc[i,1].split()
    data = []

    for i in word_dict:
        data.append(blob.count(i[0]))
        
    features.append(data) 
    
X = np.array(features)    
y = df_email.iloc[:,0].values
y = LabelEncoder().fit_transform(y)


X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)


clf=MultinomialNB()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)


print(f'Test data:\n{X_test} \npredicted_categories:\n{y_pred} \nactual_categories:\n{y_test}')
print("Accuracy:",accuracy_score(y_test,y_pred)*100)

print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))

print("Classification report:\n",classification_report(y_test,y_pred))




(5572, 2)
First 5 lines of the dataset:
   Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
Test data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 
predicted_categories:
[0 0 1 ... 0 0 0] 
actual_categories:
[0 0 0 ... 0 0 0]
Accuracy: 97.48803827751196
Confusion matrix:
 [[1418   22]
 [  20  212]]
Classification report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99      1440
           1       0.91      0.91      0.91       232

    accuracy                           0.97      1672
   macro avg       0.95      0.95      0.95      1672
weighte